### ISSUE TITLE
null analysis should merge null contracts from equivalent super methods

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-jdt/eclipse.jdt.core#2325]
In #2308 @howlger came up with this problematic snippet:
```java
import org.eclipse.jdt.annotation.NonNull;
import org.eclipse.jdt.annotation.Nullable;

interface InterfaceA {
    @Nullable Object get(); 
}

interface InterfaceB {
    @NonNull Object get(); 
}

interface InterfaceAB extends InterfaceA, InterfaceB {}

interface InterfaceBA extends InterfaceB, InterfaceA {}

class Sample {

    void ab(InterfaceAB ab) {
        @NonNull Object obj = ab.get();
                           // ^^^^^^^^
                           // ⚠ Null type mismatch (type annotations): required '@NonNull Object' but this expression has type '@Nullable Object'
                           // Expected: no "Null type mismatch" problem,
                           //           because the union of the two null constraints has to be @Nullable, the most restrictive null constraint
                           //           (@Nullable violates the null constraint given by InterfaceB; @NonNull fulfills both null constraints from InterfaceA and InterfaceB)
    }

    void ba(InterfaceBA ba) {
        @NonNull Object obj = ba.get(); // (no "Null type mismatch" as expected)
    }

}
```

Indeed null analysis should interpret the "phantom" methods in `InterfaceAB` and `InterfaceBA` as being constrained by the union of null contracts of both super methods, since any implementing class will be forced (via `The return type is incompatible with '@NonNull Object' returned from InterfaceA.get() (mismatching null constraints)`) to fulfill the stronger of both contracts.

**Comment by zhro** [comment]
It seems as though the order in which the interfaces appear after the `extends` keyword is affecting which implementation takes precedence.

This does not manifest if an implementation already exists in the source code:

```
import org.eclipse.jdt.annotation.NonNull;
import org.eclipse.jdt.annotation.Nullable;

interface INullableA {
   @Nullable Object get();
}

interface INotNullB {
   @NonNull Object get();
}

class IGetObjectClassBA implements INotNullB, INullableA {
   @Override
   public @NonNull Object get() {
      return new Object();
   }   
}

class IGetObjectClassAB implements INullableA, INotNullB {
   @Override
   public @NonNull Object get() {
      return new Object();
   }   
}

class Example2 {
   void getAB(IGetObjectClassBA ab) {
      // No "null type mismatch", as expected
       @NonNull Object obj = ab.get();
   }
   
   void getBA(IGetObjectClassAB ba) {
      // No "null type mismatch", as expected
      @NonNull Object obj = ba.get();
   }
}
```

This was misleading when trying to reproduce this bug against a jar file, because the implementation with proper annotation could exist there as a source attachment. I guess that is irrelevant, since the ECJ compiler isn't going to be run over that source code as it is locally.

**Comment by stephan-herrmann** [comment]
Let's make the coordinates of the problem space explicit:

### What ingredients are needed to produce an undesired result?
* Using only interfaces (as the top example in this issue) we see a problem, that I'm going to address
* I haven't seen an example where a variable typed to a class exhibits the problem, and until I see such example I'm convinced that this is not possible without a prior error on that class, because that's what `Mismatching null constraints` prevents
* I don't see any strong hint that jar or not jar, source or binary has an impact, even unannotated jar + .eea works fine in my experiments.

### What terminology describes the bug semantically?
* does ecj "derive" any annotations in this context?
* does any "selection" among interfaces / methods happen?
* do we support a concept of "contract merging"?

#### Re "derive": 
* if the call target is typed to a class, then this class has the method, and the annotations found at the method will be used with no further search involved (except for associating .eea).
* if the call target is typed to an interface that does not contain the method, but inherits it from multiple supers, then the compiler has to select an existing method (under the assumption that both are equivalent), but that's "selection" of a method, not "deriving" nullness.

#### Re "selection":
Here is an interesting analogy:
```java
interface InterfaceA {
    String get(); 
}
interface InterfaceB {
    Object get(); 
}

interface InterfaceAB extends InterfaceA, InterfaceB {}
interface InterfaceBA extends InterfaceB, InterfaceA {}

class Sample {
    void ab(InterfaceAB ab) {
        String obj = ab.get();
    }
    void ba(InterfaceBA ba) {
        String obj = ba.get();
    }
}
```
Now the conflict is not between annotations, but between actual return types `Object` vs. `String`. This works, demonstrating that compilers can indeed "select" the most specific method from different inherited abstract methods with equal signatures (return type is not part of the signature).

For equal return types [JLS actually has a subclause](https://docs.oracle.com/javase/specs/jls/se22/html/jls-15.html#jls-15.12.2.5) stating that "the most specific method is chosen arbitrarily among the subset of the maximally specific methods that are preferred". I will check if this "arbitrary" choice can be hijacked to pick the one with the more specific null-annotation.

#### Re "contract merge"
If the concept of method "selection" doesn't buy us a free lunch, then conceptually the cleanest description will be that some merging needs to happen:
* given that an interface inherits several equivalent methods of which none is more specific than all others (by JLS terms)
* then any implementing class will be bound by all contracts defined in different super interfaces
* which should be interpreted as a union of all inherited contracts.
* hence this union contract can also be assumed by clients of the interface with multiple supers

**Comment by stephan-herrmann** [comment]
I keep stumbling of statements like:
> This does not manifest if an implementation already exists in the source code:

It's not about source or binary, nor existence or not, but if the type of the call target has a unique implementation for both inherited methods, then all ambiguity is resolved in that type. Ergo, it never happens if call target has a class type. The same can probably achieved by a default method in an interface.

**Comment by howlger** [comment]
Besides interfaces with multiple inheritance, the issue can also be reproduced with an **abstract class** that neither implements (`public @NonNull Object get() { ... }`) nor declares (`public abstract @NonNull Object get();`) the method itself and implements multiple interfaces with different null annotations for the method:

```java
import org.eclipse.jdt.annotation.NonNull;
import org.eclipse.jdt.annotation.Nullable;

interface InterfaceA {
    @Nullable Object get(); 
}

interface InterfaceB {
    @NonNull Object get(); 
}

abstract class ClassAB implements InterfaceA, InterfaceB {}

abstract class ClassBA implements InterfaceB, InterfaceA {}

class Sample {

    void ab(ClassAB ab) {
        @NonNull Object obj = ab.get();
                           // ^^^^^^^^
                           // ⚠ Null type mismatch (type annotations): required '@NonNull Object' but this expression has type '@Nullable Object'
                           // Expected: no "Null type mismatch" problem,
                           //           because the union of the two null constraints can only be @Nullable, the most restrictive constraint
                           //           (@Nullable violates the null constraint given by InterfaceB)
    }

    void ba(ClassBA ba) {
        @NonNull Object obj = ba.get(); // expected
    }

}
```

Another analogy is exceptions for which ECJ correctly determines that the "phantom" methods throw the more specific exception:
```java
interface InterfaceA {
    void foo() throws java.io.IOException; 
}

interface InterfaceB {
    void foo() throws java.io.FileNotFoundException;
}

interface InterfaceAB extends InterfaceA, InterfaceB {}

interface InterfaceBA extends InterfaceB, InterfaceA {}

abstract class ClassAB implements InterfaceA, InterfaceB {}

abstract class ClassBA implements InterfaceB, InterfaceA {}

class Sample {

    void ab(InterfaceAB ab) throws java.io.FileNotFoundException {
        ab.foo();
    }

    void ba(InterfaceBA ba) throws java.io.FileNotFoundException {
        ba.foo();
    }

    void ab(ClassAB ab) throws java.io.FileNotFoundException {
        ab.foo();
    }
    
    void ba(ClassBA ba) throws java.io.FileNotFoundException {
        ba.foo();
    }

}
```

**Comment by stephan-herrmann** [comment]
> Besides interfaces with multiple inheritance, the issue can also be reproduced with an **abstract class** that neither implements ... nor declares ... the method itself and implements multiple interfaces with different null annotations for the method:

Correct, such abstract class is equivalent to an interface wrt the current topic.

> Another analogy is exceptions for which ECJ correctly determines that the "phantom" methods throw the more specific exception:

Right, JLS says "The thrown exception types of the most specific method are derived from the throws clauses of the maximally specific methods ..." and indeed our implementation has a dedicated class for the resulting derived / phantom method: MostSpecificExceptionMethodBinding.

Currently, the strategy in #2327 is to use null contract comparison more like method selection based on return type. Should this prove to be too coarse grained, then something like MostSpecificExceptionMethodBinding might be promising for fine-grained contract merging. But that would be considerably more effort to implement. So for now I put my money on #2327.

**Comment by zhro** [comment]
I have tried the [latest development build](https://download.eclipse.org/eclipse/downloads/drops4/I20240411-1800/) and I still see the error with the test case in this issue.

How do I test this PR? And if I have to wait for a development build, how will I know if this PR is in it for testing?

**Comment by howlger** [comment]
> @stephan-herrmann I have tried the [latest development build](https://download.eclipse.org/eclipse/downloads/drops4/I20240411-1800/) and I still see the error with the test case in this issue.
> 
> How do I test this PR? And if I have to wait for a development build, how will I know if this PR is in it for testing?

The [builds of the Eclipse project](https://download.eclipse.org/eclipse/downloads/) will get the change as soon as the pull request has been merged. To get the change already now, you can do one of the following:
- **_Help > Install New Software..._** working with the update site **[`https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2327/3/artifact/repository/target/repository/`](https://ci.eclipse.org/jdt/job/eclipse.jdt.core-Github/job/PR-2327/3/artifact/repository/target/repository/)** and after restarting do a _Project > Clean..._ (the update site URL can be found as follows: in the pull request got to the _Commits_ tab, click on the green tick at the last commit, then _Details_ of _continuous-integration/jenkins/pr-head_, in Jenkins go to _Build Artifacts_ and navigate to the `repository/target/repository` folder)
- Get the sources to compile it yourself and run it locally, with the option to make changes yourself:
   1. [Set up your IDE as described here](https://github.com/eclipse-jdt/.github/blob/main/CONTRIBUTING.md)
   2. Copy the URL of the pull request: **`https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2327`**
   3. In Eclipse do **_Fetch GitHub Pull Request_**, e.g. via _Find Actions_ (Ctrl+3) or via right-clicking the Git repository in the _Git Repositories_ view (with the previous step the dialog is prefilled and you just have to hit _Finish_)

**Comment by zhro** [comment]
Seems to be working as expected. Thank you so much. I hope that this gets merged soon.

**Comment by brychcy** [comment]
Hi Stephan!

(As this is pretty fresh, I'll simply reopen this - hope that's ok)

The change for this causes a new compile error in the following example: (only if annotation based null analysis is enabled even though no annotations are used): 
```
package test;

interface EntityManager {
	public <T> T merge(T entity);
}

interface HibernateEntityManager extends EntityManager {
}

interface Session extends HibernateEntityManager, EntityManager {
	Object merge(Object object);
}

class Test {
	void f(Session session) {
		session.merge(new Test()); // Error: The method merge(Object) is ambiguous for the type Session
	}
}
```

**Comment by howlger** [comment]
I can confirm that the following **error** is shown **in I20240411** (containing https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2327), but not in 4.32M1 (not containing https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2327) if and only if
- `org.eclipse.jdt.annotation_2.3.0.v20240111-2306.jar` has been added to Build Path, and
- annotation-based null analysis has been enabled

```java
interface I {
	<T> T m(T t);
}

interface I2 extends I {
	@SuppressWarnings("unchecked")
	Object m(Object obj);
}

class Sample {
	void sample(I2 i2) {
		i2.m(new Sample()); // Error: The method m(Object) is ambiguous for the type I2
	}
}
```

**Comment by zhro** [comment]
Are there any other examples where this occurs other than when passing to a method which has an argument of type `Object`?

**Comment by stephan-herrmann** [comment]
Thanks, @brychcy for spotting my stupid error and providing a succinct test case! :smile: 

Regression is fixed in #2390
