### ISSUE TITLE
Record Javadocs not shown in Content Assist suggestions.

### ISSUE THREAD

**Issue by garretwilson** [eclipse-jdt/eclipse.jdt.core#4102]
I'm using Eclipse EE 2025-06 with JDK 24.

Consider a simple `FooBar` record:

```java
/**
 * A foo bar.
 * @param foo The foo.
 * @param bar The bar.
 */
public record FooBar(String foo, String bar) {}
```

In my code I can create a `FooBar`:

```java
FooBar fooBar = new FooBar("some foo", "some bar");
fooBar.| // < - cursor
```

If I place my cursor after the newly created `fooBar`, I see Content Assist suggestions for `FooBar`, such as `FooBar.foo()`. This is correct. However none of the `FooBar` record accessors show any documentation.

For example for `FooBar.foo()` I expect to see the "The foo." in the documentation. But nothing appears. Eclipse is ignoring the Javadoc documentation for record field accessors.

Note that non record field methods such as `FooBar.getClass()` correctly show their Javadocs.

It would appear that Eclipse support of record fields is underdeveloped. See also #569.

**Comment by srikanth-sankaran** [comment]
> It would appear that Eclipse support of record fields is underdeveloped. See also eclipse-jdt/eclipse.jdt.ui#2313.

Could you elaborate what you mean by underdeveloped ? Is there more than eclipse-jdt/eclipse.jdt.ui#2313 to that characterization ??

**Comment by srikanth-sankaran** [comment]
I'll take a look.

**Comment by garretwilson** [comment]
> Could you elaborate what you mean by underdeveloped ? Is there more than eclipse-jdt/eclipse.jdt.ui#2313 to that characterization ??

Well, this issue eclipse-jdt/eclipse.jdt.core#4102 is another one.

Also, if you go to the top of the class and try to enter a parameter, like this:

```java
/**
 * A foo bar.
 * @param f| // <-- this is the cursor
 */
public record FooBar(String foo, String bar) {}
```

Pressing `Ctrl+Space` for Content Assist on any function should give me `@param foo` as an option. But for records it doesn't give me any choice at all. Eclipse doesn't understand that the _parameters_ to a record's constructor are in the Javadoc for the class. (If you want more discussion in general regarding this area, see [my question on Stack Overflow](https://stackoverflow.com/q/76352287) as well as [JDK-8309252](https://bugs.java.com/bugdatabase/view_bug?bug_id=JDK-8309252).)

It's just lots of little things like that.

**Comment by garretwilson** [comment]
Here's yet another issue with using Content Assist with Java records. Suppose I have the following record:

```java
import java.util.Objects;
import java.util.UUID;

/**
 * A type-safe reference to a foobar.
 * @param uuid The foobar UUID.
 */
public record FooBarRef(UUID uuid) {
	
  /**Validation constructor.*/
  public FooBarRef {
    Objects.re|  // <- cursor is here
  }

}
```

Note the cursor right after `Objects.re`. (My ultimate goal is to enter `Objects.requireNonNull(uuid)`. I hit `Ctrl+Space` to see options. The first one is `requireNonNull(T: Obj): T - Objects`, which is exactly what I want, so I hit `Enter`. Here is what I expect to get:

```java
  public FooBarRef {
    Objects.requireNonNull(obj|) // <- cursor is here
  }
```

However here is what I actually get:

```java
  public FooBarRef {
    Objects.re
    |  // <- cursor is here
  }
```

In other words, Content Assist in this context simply moved my cursor to the next line, and didn't actually perform the completion.

So yeah, it would appear that Eclipse support of records is underdeveloped in general.

**Comment by Madjosz** [comment]
Related/duplicate https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/931

**Comment by srikanth-sankaran** [comment]
@jarthana - per our discussion, I am assigning this to you for follow up.  See the various links from here to OpenJDK and UI tasks for background. Thanks!

**Comment by srikanth-sankaran** [comment]
Unassigning myself - I am available for code review and/or consultation.

**Comment by jarthana** [comment]
The Javadoc doesn't get picked up, because the compiler AST doesn't include the accessor (synthetic) methods. The way this works is, the completion proposal comes with a binding (in this case the `SMB`), which the Javadoc utility picks up and looks for the matching method from the Java Model cache. But the model cache is built from the compiler AST (`CompilationUnitStructureRequestor`) and will not include the accessor methods because they are not part of the compiler AST.

I have an experimental patch in my PR that shows one way this can be handled in `CompilationUnitStructureRequestor`. But, this is not the best way, IMO. We should find a way to artificially include them in the compiler AST itself. Without that, even the other synthetic methods of records, such as `equals()`, `hashCode()` will be missing their Javadoc.

**Comment by srikanth-sankaran** [comment]
> which the Javadoc utility picks up and looks for the matching method from the Java Model cache.

Can you mention the code location here ? 

How about instead of looking for the matching method, first recognize that it is an accessor, materialize the record component and look for that in the Java model cache ??

**Comment by srikanth-sankaran** [comment]
> even the other synthetic methods of records, such as equals(), hashCode() will be missing their Javadoc.

A similar approach to what is outlined for accessors ought to work here too I think. 

I'll study the PR and share comments tomorrow.

**Comment by jarthana** [comment]
> > which the Javadoc utility picks up and looks for the matching method from the Java Model cache.
> 
> Can you mention the code location here ?
> 
> How about instead of looking for the matching method, first recognize that it is an accessor, materialize the record component and look for that in the Java model cache ??

It's in jdt.ui, org.eclipse.jdt.internal.ui.text.java.AbstractJavaCompletionProposal.getAdditionalProposalInfo(IProgressMonitor) to be precise.

**Comment by srikanth-sankaran** [comment]
I believe historically the design principle is that the Java model stores only what is in the source. i.e., any synthetic artifacts generated during compilation of a source file don't populate the model. But while working with a class file and constructing the model from it, synthetic artifacts may show up.

See the javadoc for `org.eclipse.jdt.core.IType.getFields()` which reads:

```
/**
	 * Returns the fields declared by this type in the order in which they appear
	 * in the source or class file. For binary types, this includes synthetic fields.
	 * This does not include the implicit fields representing record components.
	 *
	 * @exception JavaModelException if this element does not exist or if an
	 *		exception occurs while accessing its corresponding resource.
	 * @return the fields declared by this type
	 */
```

and the javadoc for `org.eclipse.jdt.core.IType.getMethods()` which reads:

```
/**
	 * Returns the methods and constructors declared by this type.
	 * For binary types, this may include the special <code>&lt;clinit&gt;</code> method
	 * and synthetic methods.
	 * <p>
	 * The results are listed in the order in which they appear in the source or class file.
	 * </p>
	 *
	 * @exception JavaModelException if this element does not exist or if an
	 *		exception occurs while accessing its corresponding resource.
	 * @return the methods and constructors declared by this type
	 */
```

I see three problems with the above:

1. The asymmetry between `getMethods` and `getFields` in the latter mentioning implicit fields for record components and the former NOT mentioning implicit accessors and object methods for record classes is unfortunate.
2. Is it intentional the phrase `in the order they appear` is missing for `getMethods` ?
3. For `getFields` documentation, the sentence `This does not include the implicit fields representing record components.` juxtaposed with `For binary types, this includes synthetic fields.` is a source of ambiguity/confusion.

Here are some historic mentions that are worth perusing:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=495612 in particular https://bugs.eclipse.org/bugs/show_bug.cgi?id=495612#c1
https://bugs.eclipse.org/bugs/show_bug.cgi?id=214948#c20

**Comment by srikanth-sankaran** [comment]
> It's in jdt.ui, org.eclipse.jdt.internal.ui.text.java.AbstractJavaCompletionProposal.getAdditionalProposalInfo(IProgressMonitor) to be precise.

Thanks. Let us explore what sort of API points in `org.eclipse.jdt.core.CompletionProposal` would help clients figure out that the completion proposal is (a) for a synthetic accessor method (perhaps by introducing a new `org.eclipse.jdt.core.CompletionProposal.getKind()` that discriminate from `org.eclipse.jdt.core.CompletionProposal.METHOD_REF`) and (2) to allow from a mapping from the synthetic/derived member to the `state description` i.e record component that served as the proto declaration.

**Comment by srikanth-sankaran** [comment]
> I have an experimental patch in my PR that shows one way this can be handled in `CompilationUnitStructureRequestor`. But, this is not the best way, IMO. We should find a way to artificially include them in the compiler AST itself. Without that, even the other synthetic methods of records, such as `equals()`, `hashCode()` will be missing their Javadoc.

I agree it is not the best way - I don't think we want the Java model to be populated with synthetics from source - that is a departure from and violative of original design principles. 

We can first worry about how clients can be supported to handle accessors - and then deal with object methods.

**Comment by srikanth-sankaran** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.core/pull/4136 will allow for quick detection of accessors by saying

`if (methodBinding instanceof SyntheticMethodBinding smb && smb.purpose == SyntheticMethodBinding.RecordComponentReadAccess)`

and given an accessor `smb` the corresponding record component binding can be obtained by `smb.recordComponentBinding` and the source record component can be materialized via `smb.declaringClass.getRecordComponent(smb.selector);`

**Comment by srikanth-sankaran** [comment]
> (2) to allow from a mapping from the synthetic/derived member to the `state description` i.e record component that served as the proto declaration.

This may be an overkill. A client can use `org.eclipse.jdt.core.IType.getRecordComponents()` or `org.eclipse.jdt.core.IType.getRecordComponent(String)` to get the component java element once it knows it is an accessor that is proposed.

**Comment by jarthana** [comment]
The [jdt.ui PR](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/2293) depends on the new API in jdt.core and should be released after the jdt.core patch.

**Comment by srikanth-sankaran** [comment]
@noopur2507 do you want to look through the jdt.ui side of changes??

**Comment by noopur2507** [comment]
> [@noopur2507](https://github.com/noopur2507) do you want to look through the jdt.ui side of changes??

I have reviewed and responded on the jdt.ui PR.

**Comment by jarthana** [comment]
> Here's yet another issue with using Content Assist with Java records. Suppose I have the following record:
> ...
> Note the cursor right after `Objects.re`. (My ultimate goal is to enter `Objects.requireNonNull(uuid)`. I hit `Ctrl+Space` to see options. The first one is `requireNonNull(T: Obj): T - Objects`, which is exactly what I want, so I hit `Enter`. Here is what I expect to get:
> 
>   public FooBarRef {
>     Objects.requireNonNull(obj|) // <- cursor is here
>   }
> 
> However here is what I actually get:
> 
>   public FooBarRef {
>     Objects.re
>     |  // <- cursor is here
>   }

I see the problem with 4.36, but not with the latest I build. 
@srikanth-sankaran this might be fixed by your recent work in this area, perhaps?

**Comment by srikanth-sankaran** [comment]
> I see the problem with 4.36, but not with the latest I build.
> @srikanth-sankaran this might be fixed by your recent work in this area, perhaps?

I'll check.

**Comment by srikanth-sankaran** [comment]
> > I see the problem with 4.36, but not with the latest I build.
> > [@srikanth-sankaran](https://github.com/srikanth-sankaran) this might be fixed by your recent work in this area, perhaps?
> 
> I'll check.

Yes, this is fixed by https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4131 - when completion fails prior to this fix the log file can be seen to have this stack trace:

java.lang.NullPointerException: Cannot read field "initialization" because "local.declaration" is null
	at org.eclipse.jdt.internal.codeassist.InternalExtendedCompletionContext.searchVisibleVariablesAndMethods(InternalExtendedCompletionContext.java:742)

See that this symptom matches the top frame of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4131

**Comment by srikanth-sankaran** [comment]
Here are some comments. I think these can be addressed in a follow up PR:

1. Javadoc for API `org.eclipse.jdt.core.CompletionProposal.isRecordComponentAccessor()` mentions `METHOD_DECLARATION` in addition to `METHOD_REF`- The current fix requires only `METHOD_REF`  and the current implementation is not handling  `METHOD_DECLARATION`  - I suggest we drop the javadoc reference to  `METHOD_DECLARATION` - If in future it is needed, it can be enhanced

2. Please check if `org.eclipse.jdt.core.tests.model.CompletionTests16_2.testRecordSyntheticMethods()` should be proposing inaccessible private field at all. 

3. I feel it is better if `MethodProposalInfo.resolveMember continues to return null - let the internal APIs stay intact but let the client of those internal APIs recover by recognizing the special situation that is the topic of this defect

4. Can you check status of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/931 after this patch - does it need any more work ? 

After you release and an I-Build becomes available I can do some more testing and report any issues. 

Thanks Jay.

**Comment by jarthana** [comment]
> Here are some comments. I think these can be addressed in a follow up PR:
> 
>     1. Javadoc for API `org.eclipse.jdt.core.CompletionProposal.isRecordComponentAccessor()` mentions `METHOD_DECLARATION` in addition to `METHOD_REF`- The current fix requires only `METHOD_REF`  and the current implementation is not handling  `METHOD_DECLARATION`  - I suggest we drop the javadoc reference to  `METHOD_DECLARATION` - If in future it is needed, it can be enhanced

Updated in the latest PR

>     2. Please check if `org.eclipse.jdt.core.tests.model.CompletionTests16_2.testRecordSyntheticMethods()` should be proposing inaccessible private field at all.

org.eclipse.jdt.core.codeComplete.visibilityCheck controls this and the test doesn't do this check. So, it's OK.

>     3. I feel it is better if `MethodProposalInfo.resolveMember continues to return null - let the internal APIs stay intact but let the client of those internal APIs recover by recognizing the special situation that is the topic of this defect

I tried, but it appears there will be quite a bit of duplication and knowing more about the implementation of ProposalInfo. Besides, AFAICS, in other cases that getJavaElement() is called, for e.g., JavaTypeCompletionProposal, the MethodProposalInfo doesn't come into the picture. I guess we can leave it as it is. The tests pass, so I guess it is OK.

>     4. Can you check status of [JavaDoc for record components should show @param from the record definition eclipse.jdt.ui#931](https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/931) after this patch - does it need any more work ?

Yes, this is fixed and the JavadocHoverTests in jdt.ui cover this.

**Comment by srikanth-sankaran** [comment]
> I tried, but it appears there will be quite a bit of duplication and knowing more about the implementation of ProposalInfo. Besides, AFAICS, in other cases that getJavaElement() is called, for e.g., JavaTypeCompletionProposal, the MethodProposalInfo doesn't come into the picture. I guess we can leave it as it is. The tests pass, so I guess it is OK.

I suggest we do this: Raise a ticket against jdt.ui and capture the relevant comments there and say present solution works but may not be optimal or squeaky clean and a second look could be useful and let the team follow up in due course and take a call.

**Comment by jarthana** [comment]
> I suggest we do this: Raise a ticket against jdt.ui and capture the relevant comments there and say present solution works but may not be optimal or squeaky clean and a second look could be useful and let the team follow up in due course and take a call.

https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2309

**Comment by srikanth-sankaran** [comment]
> Also, if you go to the top of the class and try to enter a parameter, like this:
> 
> /**
>  * A foo bar.
>  * @param f| // <-- this is the cursor
>  */
> public record FooBar(String foo, String bar) {}
> Pressing `Ctrl+Space` for Content Assist on any function should give me `@param foo` as an option. But for records it doesn't give me any choice at all. Eclipse doesn't understand that the _parameters_ to a record's constructor are in the Javadoc for the class. (If you want more discussion in general regarding this area, see [my question on Stack Overflow](https://stackoverflow.com/q/76352287) as well as [JDK-8309252](https://bugs.java.com/bugdatabase/view_bug?bug_id=JDK-8309252).)
> 
> It's just lots of little things like that.

@jarthana - this particular issues still appears unaddressed in I20250702-1800 ? Could you spawn a separate ticket for this and follow up ? TIA

**Comment by srikanth-sankaran** [comment]
> > ```
> > ould show @param from the record definition eclipse.jdt.ui#931](https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/931) after this patch - does it need any more work ?
> > ```
> 
> 
> Yes, this is fixed and the JavadocHoverTests in jdt.ui cover this.

So any reason https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/931 should still be open ??

**Comment by jarthana** [comment]
> > > ```
> > > ould show @param from the record definition eclipse.jdt.ui#931](https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/931) after this patch - does it need any more work ?
> > > ```
> > 
> > 
> > Yes, this is fixed and the JavadocHoverTests in jdt.ui cover this.
> 
> So any reason [eclipse-jdt/eclipse.jdt.ui#931](https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/931) should still be open ??

Yes, the reported issue is fixed. But I think the fix broke what might have been working earlier. I.e., if we have a Javadoc explicitly for the component, it doesn't work now.  I am still investigating.

**Comment by jarthana** [comment]
> [@jarthana](https://github.com/jarthana) - this particular issues still appears unaddressed in I20250702-1800 ? Could you spawn a separate ticket for this and follow up ? TIA

https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4158

**Comment by garretwilson** [comment]
> Could you elaborate what you mean by underdeveloped ? Is there more than https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2313 to that characterization ??

… and eclipse-jdt/eclipse.jdt.ui#2501 .
