### ISSUE TITLE
Record patterns for generics not compiling

### ISSUE THREAD

**Issue by kriegaex** [eclipse-jdt/eclipse.jdt.core#450]
Similar to an example taken from https://openjdk.org/jeps/405, I was able to compile and run a class like this one correctly with Javac:

```java
public class RecordPatternsJava19OK {
  static void printGenericBoxString1(Box<Object> objectBox) {
    if (objectBox instanceof Box<Object>(String s)) {
      System.out.println(s);
    }
  }

  static void printGenericBoxString2(Box<String> stringBox) {
    if (stringBox instanceof Box<String>(var s)) {
      System.out.println(s);
    }
  }
}

record Box<T>(T t) {}
```

When compiling with ECJ, however, I see errors like these (different line numbers, because my own class has more methods):

```none
$ java -jar ecj-I20220928-1800.jar --enable-preview --release 19 -nowarn -d target/classes src/main/java/RecordPatternsJava19OK.java
----------
1. ERROR in C:\Users\alexa\Documents\java-src\AJ_Maven_build_with_dev-aspectj\src\main\java\RecordPatternsJava19OK.java (at line 36)
        if (objectBox instanceof Box<Object>(String s)) {
                                 ^^^
Only record types are permitted in a record pattern
----------
2. ERROR in C:\Users\alexa\Documents\java-src\AJ_Maven_build_with_dev-aspectj\src\main\java\RecordPatternsJava19OK.java (at line 42)
        if (stringBox instanceof Box<String>(var s)) {
                                 ^^^
Only record types are permitted in a record pattern
----------
3. ERROR in C:\Users\alexa\Documents\java-src\AJ_Maven_build_with_dev-aspectj\src\main\java\RecordPatternsJava19OK.java (at line 42)
        if (stringBox instanceof Box<String>(var s)) {
                                             ^^^
'var' is not allowed here
----------
3 problems (3 errors)
```

---

Related issue: A negative test throws the expected `raw deconstruction patterns are not allowed` compiler errors with Javac, but also wrong ones in ECJ:

```java
public class RecordPatternsJava19Error {
  static void erroneousTest1(Box2<Object> bo) {
    if (bo instanceof Box2(var s)) {     // Javac error: raw deconstruction patterns are not allowed
      System.out.println("I'm a box");
    }
  }

  static void erroneousTest2(Box2 b) {
    if (b instanceof Box2(var t)) {      // Javac error: raw deconstruction patterns are not allowed
      System.out.println("I'm a box");
    }
  }
}

record Box2<T>(T t) {}
```

```none
$ javac --enable-preview --release 19 -d target/classes src/main/java/RecordPatternsJava19Error.java
src\main\java\RecordPatternsJava19Error.java:3: Fehler: raw deconstruction patterns are not allowed
    if (bo instanceof Box2(var s)) {     // Error
                      ^
src\main\java\RecordPatternsJava19Error.java:9: Fehler: raw deconstruction patterns are not allowed
    if (b instanceof Box2(var t)) {      // Error


$ java -jar ecj-I20220928-1800.jar --enable-preview --release 19 -nowarn -d target/classes src/main/java/RecordPatternsJava19Error.java
----------
1. ERROR in C:\Users\alexa\Documents\java-src\AJ_Maven_build_with_dev-aspectj\src\main\java\RecordPatternsJava19Error.java (at line 3)
        if (bo instanceof Box2(var s)) {     // Javac error: raw deconstruction patterns are not allowed
                          ^^^^
Only record types are permitted in a record pattern
----------
2. ERROR in C:\Users\alexa\Documents\java-src\AJ_Maven_build_with_dev-aspectj\src\main\java\RecordPatternsJava19Error.java (at line 3)
        if (bo instanceof Box2(var s)) {     // Javac error: raw deconstruction patterns are not allowed
                               ^^^
'var' is not allowed here
----------
3. ERROR in C:\Users\alexa\Documents\java-src\AJ_Maven_build_with_dev-aspectj\src\main\java\RecordPatternsJava19Error.java (at line 9)
        if (b instanceof Box2(var t)) {      // Javac error: raw deconstruction patterns are not allowed
                         ^^^^
Only record types are permitted in a record pattern
----------
4. ERROR in C:\Users\alexa\Documents\java-src\AJ_Maven_build_with_dev-aspectj\src\main\java\RecordPatternsJava19Error.java (at line 9)
        if (b instanceof Box2(var t)) {      // Javac error: raw deconstruction patterns are not allowed
                              ^^^
'var' is not allowed here
----------
4 problems (4 errors)
```

**Comment by jarthana** [comment]
Surprised to see we haven't implemented methods like isRecord(), components() etc. for ParameterizedTypeBinding. Just moving the implementation around somehow should take care of this. I am looking into this.

**Comment by jarthana** [comment]
I have fixed the ParameterizedTypeBinding to delegate the isRecord() and components() to its type. This takes care of the pattern related issues.

**Comment by kriegaex** [comment]
@jarthana, can you please point me to a download source for an updated stand-alone ECJ JAR containing the fix? I want to compare the results to AspectJ, where I have merged in your fix already and am still seeing problems:
- `RecordPatternsJava19OK` compiles, but when actually calling method `printGenericBoxString2`, I see `java.lang.NoSuchMethodError: 'java.lang.String Box.t()'`, as if it does not like `var` there somehow. I want to check if this is an AJC or ECJ problem, but need the ECJ JAR in order to compare.
- `RecordPatternsJava19Error` should throw the errors that Javac does, but in AJC there are no compile errors, and I can call the methods during runtime, even though there should be compile errors.
- I am not sure if it is related or not, but ECJ also has exhaustiveness check problems with record patterns. Probably I should create a new bug for this, but I can also paste sample code here.

BTW, my sample code for the very superficial smoke tests we use in Aspectj just comes from the JEP. I am wondering why the JDT Core team does not also use those examples and compares the result with Javac, before deciding that the feature is complete and merging it into the main branch.

**Comment by iloveeclipse** [comment]
There is a build running now, binaries will be in ~1 hour available at https://download.eclipse.org/eclipse/downloads/drops4/I20221007-0230

**Comment by jarthana** [comment]
> @jarthana, can you please point me to a download source for an updated stand-alone ECJ JAR containing the fix? I want to compare the results to AspectJ, where I have merged in your fix already and am still seeing problems:
> 
>     * `RecordPatternsJava19OK` compiles, but when actually calling method `printGenericBoxString2`, I see `java.lang.NoSuchMethodError: 'java.lang.String Box.t()'`, as if it does not like `var` there somehow. I want to check if this is an AJC or ECJ problem, but need the ECJ JAR in order to compare.
> 
>     * `RecordPatternsJava19Error` should throw the errors that Javac does, but in AJC there are no compile errors, and I can call the methods during runtime, even though there should be compile errors.
> 
>     * I am not sure if it is related or not, but ECJ also has exhaustiveness check problems with record patterns. Probably I should create a new bug for this, but I can also paste sample code here.
> 
> 
> BTW, my sample code for the very superficial smoke tests we use in Aspectj just comes from the JEP. I am wondering why the JDT Core team does not also use those examples and compares the result with Javac, before deciding that the feature is complete and merging it into the main branch.

Just select the latest build that Andrey specified and go to the end and look for ecj*.jar. I have added test that runs the program from the testcase successfully. So, unless the testcase is different, it is unlikely to be an ECJ problem.

I think the exhaustiveness issue is being tracked here: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/398

About your last comment: we have probably said this before but here it is again; The JDT team is understaffed and we don't have the luxury that Javac has - that is to be able to work on it for months before releasing the spec and the feature. We get a very short time from the time a new feature is marked for any release. I wish I can say our support is perfect, but I can't.
Being a preview feature, things are bound to change (as we have seen in the past) and we will continue to work on the preview features in the following iterations. Having said, thank you for testing and raising bugs thus bringing the shortcomings to our notice!

**Comment by kriegaex** [comment]
It is an ECJ problem, I just checked. The result is exactly the same as with AJC, both for this issue and #455. Again, separately:

```java
/**
 * Not working as expected in ECJ/AJC, see https://github.com/eclipse-jdt/eclipse.jdt.core/issues/450
 */
public class RecordPatternsJava19Error {
  public static void main(String[] args) {
    erroneousTest1(new Box<>("A"));
    erroneousTest2(new Box<>("B"));
  }

  static void erroneousTest1(Box<Object> bo) {
    if (bo instanceof Box(var s)) {     // Javac error: raw deconstruction patterns are not allowed
      System.out.println("I'm a box");
    }
  }

  static void erroneousTest2(Box b) {
    if (b instanceof Box(var t)) {      // Javac error: raw deconstruction patterns are not allowed
      System.out.println("I'm a box");
    }
  }

  record Box<T>(T t) {}
}
```

```text
$ javac -J-Duser.language=en --enable-preview --release 19 -nowarn -d target/classes src/main/java/RecordPatternsJava19Error.java
src\main\java\RecordPatternsJava19Error.java:11: error: raw deconstruction patterns are not allowed
    if (bo instanceof Box(var s)) {     // Javac error: raw deconstruction patterns are not allowed
                      ^
src\main\java\RecordPatternsJava19Error.java:17: error: raw deconstruction patterns are not allowed
    if (b instanceof Box(var t)) {      // Javac error: raw deconstruction patterns are not allowed
                     ^
Note: src\main\java\RecordPatternsJava19Error.java uses preview features of Java SE 19.
Note: Recompile with -Xlint:preview for details.
2 errors

$ java -jar ecj-I20221007-0230.jar --enable-preview --release 19 -nowarn -d target/classes src/main/java/RecordPatternsJava19Error.java

$ java --enable-preview -cp target/classes RecordPatternsJava19Error
I'm a box
I'm a box
```

See? Javac throws the expected errors, ECJ does not. And I can run the ECJ-compiled program which should not even compile.

**Comment by jarthana** [comment]
I see the problem. Reopening.

**Comment by jarthana** [comment]
Here's the relevant part from the spec (14.30.3 Properties of Patterns):
```
If the type R names a generic record class then it is a compile-time error if R is not a parameterized type.

-     Record patterns with a type that names a generic record class should use a parameterization of this class. Currently, there is no support for inference of type arguments in record patterns. This may be supported in future versions of the Java Programming Language.

```
Looks more like a convenient rule than anything else. Nevertheless, I will add a new error for this.

**Comment by kriegaex** [comment]
The following is a meta comment unrelated to the actual technical issue at hand:

> About your last comment: we have probably said this before but here it is again; The JDT team is understaffed

I am well aware and already explicitly acknowledged that on the mailing list. Being in the same situation as only active committer in AspectJ, I do sympathise.

> Being a preview feature, things are bound to change (as we have seen in the past)

IMO, a preview feature is a first-class citizen in a Java compiler. Of course, it is going to change, but it does not mean that people do not expect to be able to use it the way it is supposed to work in preview no. x. The whole point of preview features is to try them and provide feedback, before they become final features. I suggest to rather merge a few days later than to publish the compiler with obviously incomplete Java language support. Maybe the JDT team is pressurising itself more than necessary. Or maybe it is a matter of communication, and the merged version should still be called beta until the preview feature implementation has been completed as well. I am not sure where the pressure comes from.

Another potentially helpful idea is to always try to incorporate code examples from the corresponding JEPs into the test bed and compare the behaviour to Javac. Of course, that does not in any way replace implementing the JEP based on the JVM spec, but having a few obvious test cases might help to drive design and implementation and gain additional confidence before merging a beta branch into main.

Why am I obsessing about preview feature support? I know that pure Java users can always switch from ECJ to Javac, if they want to use preview or incubator features. But users of compilers for other languages, which are derived from ECJ, say GrEclipse or AspectJ, cannot just switch so easily. AspectJ users would just say, "AJC does not work with Java n". So I have two choices: To either delay the AspectJ release for Java n for potentially months in favour of snapshot builds or to release anyway and write in the release notes that preview feature support is incomplete.

> we will continue to work on the preview features in the following iterations.

Thanks for that. However, a bug like https://bugs.eclipse.org/bugs/show_bug.cgi?id=579360 (a pattern switch issue from Java 18) has not been fixed for Java 19 either, even though in the 3rd pattern switch preview the syntax has remained unchanged.

Please note: I am not urging you to magically finish new compiler versions more quickly than you reasonably can. I just want to point out that I disagree with the notion of preview features somehow not being sufficiently relevant to satisfy a later release or more thorough implementation, just because they might change. I want to be on good terms with the JDT Core team, not just because Aspectj depends on you but because I so much respect your hard work. 😊

**Comment by kriegaex** [comment]
@jarthana, I am still blocked and have not released AspectJ 1.9.19 with Java 19 support due to this issue and the other two mentioned in https://github.com/eclipse/org.aspectj/issues/184#issuecomment-1272254940. Would you mind fixing these 3 problems? I want to avoid releasing AspectJ without the fixes. Thank you so much.

**Comment by iloveeclipse** [comment]
@kriegaex : do you still have issues, also with 4.26 RC2? At least your last example should work now.

**Comment by kriegaex** [comment]
Could you please point me to a Maven-consumable or at least downloadable ECJ version I should try? It could be 4.26 RC2 or any type of passing integration build.

Merging JDT Core master into the AspectJ fork is non-trivial after https://github.com/eclipse-jdt/eclipse.jdt.core/commit/457e2221c44b49b6f38fcdfe6d1d59467a04bf75, because we only use code from the `org.eclipse.jdt.core` and `org.eclipse.jdt.compiler.apt` modules in our own Maven build. We ignore the rest of JDT Core for AspectJ. I see that lately some code has been moved to other modules, and I am too busy at the moment to analyse what needs to be done to get that working again in our own build after a merge. So I would just like to try stand-alone ECJ in order to see if the 3 issues I have - this one among them - have been resolved and it is worth the effort to merge yet.

**Comment by iloveeclipse** [comment]
4.26 RC2 (== final) is here: https://download.eclipse.org/eclipse/downloads/drops4/S-4.26RC2-202211231800/
Just scroll down to "JDT Core Batch Compiler" section.
Nightly builds are here: https://download.eclipse.org/eclipse/downloads/

**Comment by kriegaex** [comment]
The error message is somewhat different from Javac's _"raw deconstruction patterns are not allowed"_ and says _"Raw types are not allowed in record patterns"_, but I can confirm that for this issue ECJ now throws compile errors as follows:

```text
$ java -jar ecj-4.26RC2.jar --enable-preview --release 19 -nowarn -d target/classes src/main/RecordPatternsJava19Error.java
----------
1. ERROR in C:\Users\Alexander\Documents\java-src\AJ_Maven_build_with_dev-aspectj\src\main\RecordPatternsJava19Error.java (at line 11)
        if (bo instanceof Box(var s)) {     // Javac error: raw deconstruction patterns are not allowed
                          ^^^
Raw types are not allowed in record patterns
----------
2. ERROR in C:\Users\Alexander\Documents\java-src\AJ_Maven_build_with_dev-aspectj\src\main\RecordPatternsJava19Error.java (at line 17)
        if (b instanceof Box(var t)) {      // Javac error: raw deconstruction patterns are not allowed
                         ^^^
Raw types are not allowed in record patterns
----------
2 problems (2 errors)
```

**Comment by iloveeclipse** [comment]
So can we close this bug now?

**Comment by kriegaex** [comment]
I guess so. Thank you very much.
