### ISSUE TITLE
Incorrect warning for `@SuppressWarnings` for `forRemoval` deprecations in light of JEP 277.

### ISSUE THREAD

**Issue by garretwilson** [eclipse-jdt/eclipse.jdt.core#4579]
[JEP 277](https://openjdk.org/jeps/277) changed the rules about how warnings are admitted by the compiler. If `foo()` is marked `@Deprecated(forRemoval = true)`, and calls `bar()` which is also marked as `@Deprecated(forRemoval = true)`, `javac` will still emit a warning that `foo()` is using a for-removal deprecated method. The workaround is to use `@SuppressWarnings("removal")`.

```java
@SuppressWarnings("removal")
@Deprecated(forRemoval = true)
public void foo() {
  bar();
}

@Deprecated(forRemoval = true)
public void bar() {
}
```

However Eclipse gives a warning when `@SuppressWarnings("removal")` is used:

> Unnecessary @SuppressWarnings("removal")

But the warning is _not_ unnecessary, according to JEP 277, because JEP 277 considers `forRemoval = true` to have stronger semantics that doesn't suppress warnings automatically, even though both methods are deprecated, because `forRemoval` has been specified.

Please bring Eclipse warning behavior in line with JEP 277 so that my suppressing one warning I don't get another different, incorrect warning in Eclipse.

Note that the solution is _not_ for me to go into my settings and lower or disable the level of the Eclipse warning, because I do want this warning in _valid_ instances. I just don't want the warning in _invalid_ instances. This is an Eclipse bug, not an incorrect setting.

I'm using Eclipse EE 2025-09 (4.37.0) with Java 25. This particular project is using Java 21.

**Comment by stephan-herrmann** [comment]
Hi @garretwilson this report comes at a good time when the entire area about deprecation is still warm, see https://github.com/eclipse-jdt/eclipse.jdt.core/issues/4572 and/or https://eclipse.dev/eclipse/markdown/?f=news/4.38/jdt.md#changes-concerning-deprecation-warnings

**Comment by stephan-herrmann** [comment]
Apparently I was a bit in a haste at the time of https://bugs.eclipse.org/bugs/show_bug.cgi?id=517326#c2

> Open issues:
> - Need tests for deprecation for removal inside deprecated code
>  (should trigger warning/error!)
>  See the table in http://openjdk.java.net/jeps/277

Consequences:
* bug was opened as https://bugs.eclipse.org/bugs/show_bug.cgi?id=517332
* and moved to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2489

**Comment by stephan-herrmann** [comment]
If anyone wants to give it a try:  `Scope.isInsideDeprecatedCode()` should only be used for an excuse if it has been established that we have `TagBits.AnnotationDeprecated` and not `TagBits.AnnotationTerminallyDeprecated`.

**Comment by garretwilson** [comment]
Did this ever get fixed? I'm still seeing it:

```
Version: 2026-03 (4.39.0)
Build id: 20260305-0817
```

**Comment by stephan-herrmann** [comment]
> Did this ever get fixed? I'm still seeing it:

The general issue of calling terminally-deprecated code from terminally-deprecated code should be fixed by #4595 

In the example given here, there's one more factor at play: warning and necessity of suppressing work as expected **if caller and callee reside in different compilation units**. Within the same compilation units different rules are at play.

**Comment by garretwilson** [comment]
@stephan-herrmann I'm not sure I understood your response in the context of my intention. Maybe I should have made my intention clearer.

This ticket was opened up with a description of a problem.

1. Was the problem described in this ticket fixed?
2. If the specific problem described in this ticket was not fixed, why was this ticket closed?

**Comment by stephan-herrmann** [comment]
> This ticket was opened up with a description of a problem.

There's one thing left to guess from the description: do both parts of the code example reside in the same class or compilation unit? It might come as a surprise but this question has significance in this context.

**Comment by stephan-herrmann** [comment]
To be even more explicit about the status:
```java
public class X extends Y {
	@SuppressWarnings("removal")
	@Deprecated(forRemoval = true)
	public void foo(Y y) {
		bar();
	}
}
class Y {
	@Deprecated(forRemoval = true)
	public void bar() {
	}
}
```
Accepted by ecj since #4595 (4.38)


```java
public class X {
	@SuppressWarnings("removal")
	@Deprecated(forRemoval = true)
	public void foo() {
		bar();
	}

	@Deprecated(forRemoval = true)
	public void bar() {
	}
}
```
produces:
```
----------
1. WARNING in /tmp/X.java (at line 2)
        @SuppressWarnings("removal")
                          ^^^^^^^^^
Unnecessary @SuppressWarnings("removal")
----------
1 problem (1 warning)
```

This is due to the following rule from [JLS 9.6.4.6](https://docs.oracle.com/javase/specs/jls/se26/html/jls-9.html#jls-9.6.4.6):
> A Java compiler must produce a removal warning [...] unless:
> * [...]
> * The declaration where the use appears and the declaration of the terminally deprecated program element are both within the same outermost class

Since here `foo()` and `bar()` are in the same outermost class `X`, the exception applies, and no warning should be raised. Hence suppressing is unnecessary.

@garretwilson  let me know if you see anything still amiss.

**Comment by garretwilson** [comment]
@stephan-herrmann thank you for your replies. Honestly, in the middle of a big ticket I thought I ran into this problem remaining in the latest Eclipse, but now I can't find where it was. 😅 Now that you've confirmed this ticket was correctly closed because this should be fixed, if I can find it again I'll report back. Have a great week.
