### ISSUE TITLE
Change pom.xml modelVersion from "4.0" to "4.0.0"

### ISSUE THREAD

**Issue by fransvanbuul** [eclipse-jdt/eclipse.jdt.core#461]
In the JDT Core [published pom](https://repo1.maven.org/maven2/org/eclipse/jdt/org.eclipse.jdt.core/3.31.0/org.eclipse.jdt.core-3.31.0.pom), the "modelVersion" is set to "4.0". As per the [Maven docs](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html), this should be "4.0.0".

This doesn't really break anything, but it creates an error message everytime my (otherwise pristine) Gradle build runs:

`
Errors occurred while build effective model from C:\Users\xxxxx\.gradle\caches\modules-2\files-2.1\org.eclipse.jdt\org.eclipse.jdt.core\3.31.0\6940726f829e8aa123374a4ccac8225f5dd0a3c0\org.eclipse.jdt.core-3.31.0.pom:
        'modelVersion' must be one of [4.0.0] but is '4.0'. in org.eclipse.jdt:org.eclipse.jdt.core:3.31.0
`

Could you fix this?
Thanks in advance!
Frans

**Comment by xamde** [comment]
I've run into the same problem, but for me it is breaking a Maven build

**Comment by xamde** [comment]
The current version in git is already fixed, so we are just waiting for the next release

**Comment by Lucas3oo** [comment]
Seems that many of the eclipse artefacts have this issue.
E.g https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.core.expressions/3.8.200/org.eclipse.core.expressions-3.8.200.pom is also using "4.0" instead of "4.0.0" as model version so we still get a similar warning.

**Comment by srikanth-sankaran** [comment]
@iloveeclipse @jarthana - what is the status/validity of this ?? Looks like a trivial fix if problem is real. Sorry I am clueless so don't want to work on it myself

**Comment by iloveeclipse** [comment]
I'm not maven expert, so no idea.
@akurtakov ?

**Comment by akurtakov** [comment]
FYI  deployed poms are not the poms used during development but rather a generated ones after the release (https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/eclipse.platform.releng/publish-to-maven-central) and these hand crafter pom files were not quite good in the past. Latest deployed pom https://repo1.maven.org/maven2/org/eclipse/jdt/org.eclipse.jdt.core/3.36.0/org.eclipse.jdt.core-3.36.0.pom uses 4.0.0 so the tool seems to generate proper modelVersion now. Closing.
